services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8005:8000"
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DB_HOST}:${DB_PORT}/${POSTGRES_DB}
      LOG_DIR: /app/logs
    restart: always
  ui:
    container_name: md_editor_ui
    build:
      context: ./ui
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://127.0.0.1:8005}
    environment:
      PORT: "3045"
    ports:
      - "3045:3045"
    depends_on:
      - api
    restart: always
